# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'RememberWord' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RememberWord

pod 'AFNetworking', '~> 3.0'
pod 'Masonry'
pod 'SVProgressHUD', '~> 2.0'
pod 'MJRefresh'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
pod 'Bugly'
pod 'FTPopOverMenu'
pod 'HMSegmentedControl'

end
